/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RecipeFormData } from "./components/recipe-form/recipe-form";
export { RecipeFormData } from "./components/recipe-form/recipe-form";
export namespace Components {
    interface FavoriteButton {
        /**
          * @default false
         */
        "isFavorite": boolean;
        /**
          * @default ''
         */
        "recipeId": string;
        /**
          * @default false
         */
        "showLabel": boolean;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * @default 'button'
         */
        "variant": 'icon' | 'button';
    }
    interface FilterPanel {
        /**
          * @default '[]'
         */
        "areas": string;
        /**
          * @default '[]'
         */
        "categories": string;
        /**
          * @default ''
         */
        "selectedArea": string;
        /**
          * @default ''
         */
        "selectedCategory": string;
        /**
          * @default 'default'
         */
        "sortBy": string;
    }
    interface LoadingSpinner {
        /**
          * @default false
         */
        "fullPage": boolean;
        /**
          * @default ''
         */
        "message": string;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
    }
    interface MealPlanCard {
        /**
          * @default ''
         */
        "day": string;
        /**
          * @default false
         */
        "isEmpty": boolean;
        /**
          * @default 'dinner'
         */
        "mealType": string;
        /**
          * @default ''
         */
        "recipeId": string;
        /**
          * @default ''
         */
        "recipeImage": string;
        /**
          * @default ''
         */
        "recipeTitle": string;
    }
    interface RatingStars {
        /**
          * @default 5
         */
        "maxRating": number;
        /**
          * @default 0
         */
        "rating": number;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default true
         */
        "showValue": boolean;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
    }
    interface RecipeBadge {
        /**
          * @default ''
         */
        "icon": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * @default 'tag'
         */
        "variant": 'category' | 'area' | 'tag' | 'user' | 'success' | 'warning' | 'error' | 'info';
    }
    interface RecipeCard {
        /**
          * @default ''
         */
        "area": string;
        /**
          * @default ''
         */
        "category": string;
        /**
          * @default ''
         */
        "cookTime": string;
        /**
          * @default ''
         */
        "image": string;
        /**
          * @default false
         */
        "isFavorite": boolean;
        /**
          * @default false
         */
        "isUserCreated": boolean;
        /**
          * @default ''
         */
        "recipeId": string;
        /**
          * @default ''
         */
        "recipeTitle": string;
        /**
          * @default ''
         */
        "servings": string;
    }
    interface RecipeForm {
        /**
          * @default '[]'
         */
        "categories": string;
        /**
          * @default false
         */
        "isEditing": boolean;
        /**
          * @default '{}'
         */
        "recipeData": string;
    }
    interface RecipeModal {
        /**
          * @default ''
         */
        "modalTitle": string;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large' | 'fullscreen';
    }
    interface SearchBar {
        /**
          * @default 400
         */
        "debounceMs": number;
        /**
          * @default 'Search recipes...'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface FavoriteButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFavoriteButtonElement;
}
export interface FilterPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFilterPanelElement;
}
export interface MealPlanCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMealPlanCardElement;
}
export interface RatingStarsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRatingStarsElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeCardElement;
}
export interface RecipeFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeFormElement;
}
export interface RecipeModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeModalElement;
}
export interface SearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchBarElement;
}
declare global {
    interface HTMLFavoriteButtonElementEventMap {
        "favoriteToggle": { id: string; isFavorite: boolean };
    }
    interface HTMLFavoriteButtonElement extends Components.FavoriteButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFavoriteButtonElementEventMap>(type: K, listener: (this: HTMLFavoriteButtonElement, ev: FavoriteButtonCustomEvent<HTMLFavoriteButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFavoriteButtonElementEventMap>(type: K, listener: (this: HTMLFavoriteButtonElement, ev: FavoriteButtonCustomEvent<HTMLFavoriteButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFavoriteButtonElement: {
        prototype: HTMLFavoriteButtonElement;
        new (): HTMLFavoriteButtonElement;
    };
    interface HTMLFilterPanelElementEventMap {
        "filterChange": { category: string; area: string; sortBy: string };
        "filterReset": void;
    }
    interface HTMLFilterPanelElement extends Components.FilterPanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFilterPanelElementEventMap>(type: K, listener: (this: HTMLFilterPanelElement, ev: FilterPanelCustomEvent<HTMLFilterPanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFilterPanelElementEventMap>(type: K, listener: (this: HTMLFilterPanelElement, ev: FilterPanelCustomEvent<HTMLFilterPanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFilterPanelElement: {
        prototype: HTMLFilterPanelElement;
        new (): HTMLFilterPanelElement;
    };
    interface HTMLLoadingSpinnerElement extends Components.LoadingSpinner, HTMLStencilElement {
    }
    var HTMLLoadingSpinnerElement: {
        prototype: HTMLLoadingSpinnerElement;
        new (): HTMLLoadingSpinnerElement;
    };
    interface HTMLMealPlanCardElementEventMap {
        "mealRemove": { day: string; mealType: string };
        "mealSlotClick": { day: string; mealType: string };
        "viewRecipe": string;
    }
    interface HTMLMealPlanCardElement extends Components.MealPlanCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMealPlanCardElementEventMap>(type: K, listener: (this: HTMLMealPlanCardElement, ev: MealPlanCardCustomEvent<HTMLMealPlanCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMealPlanCardElementEventMap>(type: K, listener: (this: HTMLMealPlanCardElement, ev: MealPlanCardCustomEvent<HTMLMealPlanCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMealPlanCardElement: {
        prototype: HTMLMealPlanCardElement;
        new (): HTMLMealPlanCardElement;
    };
    interface HTMLRatingStarsElementEventMap {
        "ratingChange": number;
    }
    interface HTMLRatingStarsElement extends Components.RatingStars, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRatingStarsElementEventMap>(type: K, listener: (this: HTMLRatingStarsElement, ev: RatingStarsCustomEvent<HTMLRatingStarsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRatingStarsElementEventMap>(type: K, listener: (this: HTMLRatingStarsElement, ev: RatingStarsCustomEvent<HTMLRatingStarsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRatingStarsElement: {
        prototype: HTMLRatingStarsElement;
        new (): HTMLRatingStarsElement;
    };
    interface HTMLRecipeBadgeElement extends Components.RecipeBadge, HTMLStencilElement {
    }
    var HTMLRecipeBadgeElement: {
        prototype: HTMLRecipeBadgeElement;
        new (): HTMLRecipeBadgeElement;
    };
    interface HTMLRecipeCardElementEventMap {
        "cardClick": string;
        "favoriteToggle": { id: string; isFavorite: boolean };
        "addToMealPlan": string;
        "editRecipe": string;
        "deleteRecipe": string;
    }
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLRecipeFormElementEventMap {
        "formSubmit": RecipeFormData;
        "formCancel": void;
    }
    interface HTMLRecipeFormElement extends Components.RecipeForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeFormElementEventMap>(type: K, listener: (this: HTMLRecipeFormElement, ev: RecipeFormCustomEvent<HTMLRecipeFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeFormElementEventMap>(type: K, listener: (this: HTMLRecipeFormElement, ev: RecipeFormCustomEvent<HTMLRecipeFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeFormElement: {
        prototype: HTMLRecipeFormElement;
        new (): HTMLRecipeFormElement;
    };
    interface HTMLRecipeModalElementEventMap {
        "modalClose": void;
        "modalConfirm": void;
    }
    interface HTMLRecipeModalElement extends Components.RecipeModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeModalElementEventMap>(type: K, listener: (this: HTMLRecipeModalElement, ev: RecipeModalCustomEvent<HTMLRecipeModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeModalElementEventMap>(type: K, listener: (this: HTMLRecipeModalElement, ev: RecipeModalCustomEvent<HTMLRecipeModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeModalElement: {
        prototype: HTMLRecipeModalElement;
        new (): HTMLRecipeModalElement;
    };
    interface HTMLSearchBarElementEventMap {
        "searchChange": string;
        "searchSubmit": string;
        "searchClear": void;
    }
    interface HTMLSearchBarElement extends Components.SearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSearchBarElementEventMap>(type: K, listener: (this: HTMLSearchBarElement, ev: SearchBarCustomEvent<HTMLSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSearchBarElementEventMap>(type: K, listener: (this: HTMLSearchBarElement, ev: SearchBarCustomEvent<HTMLSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSearchBarElement: {
        prototype: HTMLSearchBarElement;
        new (): HTMLSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "favorite-button": HTMLFavoriteButtonElement;
        "filter-panel": HTMLFilterPanelElement;
        "loading-spinner": HTMLLoadingSpinnerElement;
        "meal-plan-card": HTMLMealPlanCardElement;
        "rating-stars": HTMLRatingStarsElement;
        "recipe-badge": HTMLRecipeBadgeElement;
        "recipe-card": HTMLRecipeCardElement;
        "recipe-form": HTMLRecipeFormElement;
        "recipe-modal": HTMLRecipeModalElement;
        "search-bar": HTMLSearchBarElement;
    }
}
declare namespace LocalJSX {
    interface FavoriteButton {
        /**
          * @default false
         */
        "isFavorite"?: boolean;
        "onFavoriteToggle"?: (event: FavoriteButtonCustomEvent<{ id: string; isFavorite: boolean }>) => void;
        /**
          * @default ''
         */
        "recipeId"?: string;
        /**
          * @default false
         */
        "showLabel"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * @default 'button'
         */
        "variant"?: 'icon' | 'button';
    }
    interface FilterPanel {
        /**
          * @default '[]'
         */
        "areas"?: string;
        /**
          * @default '[]'
         */
        "categories"?: string;
        "onFilterChange"?: (event: FilterPanelCustomEvent<{ category: string; area: string; sortBy: string }>) => void;
        "onFilterReset"?: (event: FilterPanelCustomEvent<void>) => void;
        /**
          * @default ''
         */
        "selectedArea"?: string;
        /**
          * @default ''
         */
        "selectedCategory"?: string;
        /**
          * @default 'default'
         */
        "sortBy"?: string;
    }
    interface LoadingSpinner {
        /**
          * @default false
         */
        "fullPage"?: boolean;
        /**
          * @default ''
         */
        "message"?: string;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
    }
    interface MealPlanCard {
        /**
          * @default ''
         */
        "day"?: string;
        /**
          * @default false
         */
        "isEmpty"?: boolean;
        /**
          * @default 'dinner'
         */
        "mealType"?: string;
        "onMealRemove"?: (event: MealPlanCardCustomEvent<{ day: string; mealType: string }>) => void;
        "onMealSlotClick"?: (event: MealPlanCardCustomEvent<{ day: string; mealType: string }>) => void;
        "onViewRecipe"?: (event: MealPlanCardCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "recipeId"?: string;
        /**
          * @default ''
         */
        "recipeImage"?: string;
        /**
          * @default ''
         */
        "recipeTitle"?: string;
    }
    interface RatingStars {
        /**
          * @default 5
         */
        "maxRating"?: number;
        "onRatingChange"?: (event: RatingStarsCustomEvent<number>) => void;
        /**
          * @default 0
         */
        "rating"?: number;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default true
         */
        "showValue"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
    }
    interface RecipeBadge {
        /**
          * @default ''
         */
        "icon"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * @default 'tag'
         */
        "variant"?: 'category' | 'area' | 'tag' | 'user' | 'success' | 'warning' | 'error' | 'info';
    }
    interface RecipeCard {
        /**
          * @default ''
         */
        "area"?: string;
        /**
          * @default ''
         */
        "category"?: string;
        /**
          * @default ''
         */
        "cookTime"?: string;
        /**
          * @default ''
         */
        "image"?: string;
        /**
          * @default false
         */
        "isFavorite"?: boolean;
        /**
          * @default false
         */
        "isUserCreated"?: boolean;
        "onAddToMealPlan"?: (event: RecipeCardCustomEvent<string>) => void;
        "onCardClick"?: (event: RecipeCardCustomEvent<string>) => void;
        "onDeleteRecipe"?: (event: RecipeCardCustomEvent<string>) => void;
        "onEditRecipe"?: (event: RecipeCardCustomEvent<string>) => void;
        "onFavoriteToggle"?: (event: RecipeCardCustomEvent<{ id: string; isFavorite: boolean }>) => void;
        /**
          * @default ''
         */
        "recipeId"?: string;
        /**
          * @default ''
         */
        "recipeTitle"?: string;
        /**
          * @default ''
         */
        "servings"?: string;
    }
    interface RecipeForm {
        /**
          * @default '[]'
         */
        "categories"?: string;
        /**
          * @default false
         */
        "isEditing"?: boolean;
        "onFormCancel"?: (event: RecipeFormCustomEvent<void>) => void;
        "onFormSubmit"?: (event: RecipeFormCustomEvent<RecipeFormData>) => void;
        /**
          * @default '{}'
         */
        "recipeData"?: string;
    }
    interface RecipeModal {
        /**
          * @default ''
         */
        "modalTitle"?: string;
        "onModalClose"?: (event: RecipeModalCustomEvent<void>) => void;
        "onModalConfirm"?: (event: RecipeModalCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large' | 'fullscreen';
    }
    interface SearchBar {
        /**
          * @default 400
         */
        "debounceMs"?: number;
        "onSearchChange"?: (event: SearchBarCustomEvent<string>) => void;
        "onSearchClear"?: (event: SearchBarCustomEvent<void>) => void;
        "onSearchSubmit"?: (event: SearchBarCustomEvent<string>) => void;
        /**
          * @default 'Search recipes...'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface FavoriteButtonAttributes {
        "recipeId": string;
        "isFavorite": boolean;
        "size": 'small' | 'medium' | 'large';
        "showLabel": boolean;
        "variant": 'icon' | 'button';
    }
    interface FilterPanelAttributes {
        "categories": string;
        "areas": string;
        "selectedCategory": string;
        "selectedArea": string;
        "sortBy": string;
    }
    interface LoadingSpinnerAttributes {
        "size": 'small' | 'medium' | 'large';
        "message": string;
        "fullPage": boolean;
    }
    interface MealPlanCardAttributes {
        "day": string;
        "mealType": string;
        "recipeId": string;
        "recipeTitle": string;
        "recipeImage": string;
        "isEmpty": boolean;
    }
    interface RatingStarsAttributes {
        "rating": number;
        "maxRating": number;
        "readonly": boolean;
        "size": 'small' | 'medium' | 'large';
        "showValue": boolean;
    }
    interface RecipeBadgeAttributes {
        "label": string;
        "variant": 'category' | 'area' | 'tag' | 'user' | 'success' | 'warning' | 'error' | 'info';
        "size": 'small' | 'medium' | 'large';
        "icon": string;
    }
    interface RecipeCardAttributes {
        "recipeId": string;
        "recipeTitle": string;
        "image": string;
        "category": string;
        "area": string;
        "isFavorite": boolean;
        "isUserCreated": boolean;
        "cookTime": string;
        "servings": string;
    }
    interface RecipeFormAttributes {
        "recipeData": string;
        "isEditing": boolean;
        "categories": string;
    }
    interface RecipeModalAttributes {
        "open": boolean;
        "modalTitle": string;
        "size": 'small' | 'medium' | 'large' | 'fullscreen';
    }
    interface SearchBarAttributes {
        "placeholder": string;
        "value": string;
        "debounceMs": number;
    }

    interface IntrinsicElements {
        "favorite-button": Omit<FavoriteButton, keyof FavoriteButtonAttributes> & { [K in keyof FavoriteButton & keyof FavoriteButtonAttributes]?: FavoriteButton[K] } & { [K in keyof FavoriteButton & keyof FavoriteButtonAttributes as `attr:${K}`]?: FavoriteButtonAttributes[K] } & { [K in keyof FavoriteButton & keyof FavoriteButtonAttributes as `prop:${K}`]?: FavoriteButton[K] };
        "filter-panel": Omit<FilterPanel, keyof FilterPanelAttributes> & { [K in keyof FilterPanel & keyof FilterPanelAttributes]?: FilterPanel[K] } & { [K in keyof FilterPanel & keyof FilterPanelAttributes as `attr:${K}`]?: FilterPanelAttributes[K] } & { [K in keyof FilterPanel & keyof FilterPanelAttributes as `prop:${K}`]?: FilterPanel[K] };
        "loading-spinner": Omit<LoadingSpinner, keyof LoadingSpinnerAttributes> & { [K in keyof LoadingSpinner & keyof LoadingSpinnerAttributes]?: LoadingSpinner[K] } & { [K in keyof LoadingSpinner & keyof LoadingSpinnerAttributes as `attr:${K}`]?: LoadingSpinnerAttributes[K] } & { [K in keyof LoadingSpinner & keyof LoadingSpinnerAttributes as `prop:${K}`]?: LoadingSpinner[K] };
        "meal-plan-card": Omit<MealPlanCard, keyof MealPlanCardAttributes> & { [K in keyof MealPlanCard & keyof MealPlanCardAttributes]?: MealPlanCard[K] } & { [K in keyof MealPlanCard & keyof MealPlanCardAttributes as `attr:${K}`]?: MealPlanCardAttributes[K] } & { [K in keyof MealPlanCard & keyof MealPlanCardAttributes as `prop:${K}`]?: MealPlanCard[K] };
        "rating-stars": Omit<RatingStars, keyof RatingStarsAttributes> & { [K in keyof RatingStars & keyof RatingStarsAttributes]?: RatingStars[K] } & { [K in keyof RatingStars & keyof RatingStarsAttributes as `attr:${K}`]?: RatingStarsAttributes[K] } & { [K in keyof RatingStars & keyof RatingStarsAttributes as `prop:${K}`]?: RatingStars[K] };
        "recipe-badge": Omit<RecipeBadge, keyof RecipeBadgeAttributes> & { [K in keyof RecipeBadge & keyof RecipeBadgeAttributes]?: RecipeBadge[K] } & { [K in keyof RecipeBadge & keyof RecipeBadgeAttributes as `attr:${K}`]?: RecipeBadgeAttributes[K] } & { [K in keyof RecipeBadge & keyof RecipeBadgeAttributes as `prop:${K}`]?: RecipeBadge[K] };
        "recipe-card": Omit<RecipeCard, keyof RecipeCardAttributes> & { [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K] };
        "recipe-form": Omit<RecipeForm, keyof RecipeFormAttributes> & { [K in keyof RecipeForm & keyof RecipeFormAttributes]?: RecipeForm[K] } & { [K in keyof RecipeForm & keyof RecipeFormAttributes as `attr:${K}`]?: RecipeFormAttributes[K] } & { [K in keyof RecipeForm & keyof RecipeFormAttributes as `prop:${K}`]?: RecipeForm[K] };
        "recipe-modal": Omit<RecipeModal, keyof RecipeModalAttributes> & { [K in keyof RecipeModal & keyof RecipeModalAttributes]?: RecipeModal[K] } & { [K in keyof RecipeModal & keyof RecipeModalAttributes as `attr:${K}`]?: RecipeModalAttributes[K] } & { [K in keyof RecipeModal & keyof RecipeModalAttributes as `prop:${K}`]?: RecipeModal[K] };
        "search-bar": Omit<SearchBar, keyof SearchBarAttributes> & { [K in keyof SearchBar & keyof SearchBarAttributes]?: SearchBar[K] } & { [K in keyof SearchBar & keyof SearchBarAttributes as `attr:${K}`]?: SearchBarAttributes[K] } & { [K in keyof SearchBar & keyof SearchBarAttributes as `prop:${K}`]?: SearchBar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "favorite-button": LocalJSX.IntrinsicElements["favorite-button"] & JSXBase.HTMLAttributes<HTMLFavoriteButtonElement>;
            "filter-panel": LocalJSX.IntrinsicElements["filter-panel"] & JSXBase.HTMLAttributes<HTMLFilterPanelElement>;
            "loading-spinner": LocalJSX.IntrinsicElements["loading-spinner"] & JSXBase.HTMLAttributes<HTMLLoadingSpinnerElement>;
            "meal-plan-card": LocalJSX.IntrinsicElements["meal-plan-card"] & JSXBase.HTMLAttributes<HTMLMealPlanCardElement>;
            "rating-stars": LocalJSX.IntrinsicElements["rating-stars"] & JSXBase.HTMLAttributes<HTMLRatingStarsElement>;
            "recipe-badge": LocalJSX.IntrinsicElements["recipe-badge"] & JSXBase.HTMLAttributes<HTMLRecipeBadgeElement>;
            "recipe-card": LocalJSX.IntrinsicElements["recipe-card"] & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            "recipe-form": LocalJSX.IntrinsicElements["recipe-form"] & JSXBase.HTMLAttributes<HTMLRecipeFormElement>;
            "recipe-modal": LocalJSX.IntrinsicElements["recipe-modal"] & JSXBase.HTMLAttributes<HTMLRecipeModalElement>;
            "search-bar": LocalJSX.IntrinsicElements["search-bar"] & JSXBase.HTMLAttributes<HTMLSearchBarElement>;
        }
    }
}
